version: 2
aliases:
  - &install-essential
    name: Install curl
    command: |
      apt update && apt install curl build-essential -y
  - &setup-nodejs
    name: setup nodejs
    command: |
      curl -sL https://deb.nodesource.com/setup_12.x | bash -
      apt-get install -y nodejs
  - &link-and-execute
    name: Run envinfo
    command: |
      npm run build
      npm link
      envinfo

jobs:
  node10-test:
    working_directory: ~/repo
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: *link-and-execute
  alpine-test:
    working_directory: ~/repo
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: *link-and-execute
  ubuntu-test:
    working_directory: ~/repo
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: *install-essential
      - run: *setup-nodejs
      - run: npm install
      - run: npm run test
      - run: *link-and-execute
  debian-test:
    working_directory: ~/repo
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: *link-and-execute
  centos-test:
    working_directory: ~/repo
    docker:
      - image: centos
    steps:
      - checkout
      - run: yum install curl -y && curl -sL https://rpm.nodesource.com/setup_12.x | bash - && yum install nodejs -y
      - run: npm install
      - run: npm run test
      - run: *link-and-execute
  react-native-test:
    working_directory: ~/repo
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: *link-and-execute
  general-test:
    working_directory: ~/repo
    docker:
      - image: gengjiawen/node-build
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: *link-and-execute

workflows:
  version: 2
  build_and_test:
    jobs:
      - node10-test
      - ubuntu-test
      - alpine-test
      - debian-test
      - centos-test
      - react-native-test
      # Workaround for https://github.com/tabrindle/envinfo/issues/104
      - general-test
